### ISSUE TITLE
shops item list is reset after each server restart

### ISSUE THREAD

**Issue by ddq1** [Veradictus/Kaetram-Open#8]
As the item list for shops are stored in a json file (shops.json), this list reset at each restart of the server. if the item list was stored on mongoDb it could be set accordingly to its last state.

**Comment by Veradictus** [comment]
Good idea, I will be doing that sometime soon!

**Comment by Veradictus** [comment]
Been thinking about this for a while, I think it would be better to keep the current system. Since if anything bugs out regarding shops, a server restart resets the shops in their entirety. Adding database functionality may involve unwanted bugs. This request will be considered in the future, but I think it's fine for now.
